@startuml

usecase "/autoware_state_machine"
usecase "/ad_status_lamp_manager" #LightCoral
usecase "/dio_ros_driver"

(/autoware_state_machine) -> (/ad_status_lamp_manager) : /autoware_state_machine/state

(/ad_status_lamp_manager) -> (/dio_ros_driver) : /dio/dout0

@enduml
